### ISSUE TITLE
feat: add a loading button/screen

### ISSUE THREAD

**Issue by megabyte0x** [jcstein/gm-portal#11]
After creating the post, there is nothing a user can do or see. 

It will be great to have a loading button/screen in this.

**Comment by jcstein** [comment]
gm @megabyte0x - would you like to add a loading state? happy to have you contribute if you want! otherwise, great idea!

**Comment by jcstein** [comment]
https://www.loom.com/share/0c8d741e691b4b8ea2ae96812bf2748d
